name: Frontend CI

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches: [ "develop", "feature/*" ]
  pull_request:
    branches: [ "develop", "feature/*" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

  dependencies:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: npm ci

  code_style:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Run Linting
      run: npm run lint

  test:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Run Tests
      run: npm run test:coverage

  build:
    runs-on: ubuntu-latest
    needs: [test, code_style]
    steps:
    - name: Build Frontend
      run: npm run build

  deploy-preview:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --environment=preview --prebuilt --token=${{ secrets.VERCEL_TOKEN }}